# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dorfcUD5X36MCIWQ2-k0-qTDSaa1R9xo
"""

!pip install ultralytics

from google.colab import files
uploaded = files.upload()

from ultralytics import YOLO
from IPython.display import Image, display

# Load pretrained YOLOv8 model
model = YOLO("yolov8n.pt")   # nano model (fast)

# Run detection
results = model("img.jpg", save=True)

# Display output image
display(Image(filename="runs/detect/predict/img.jpg"))

# Print detected objects
for r in results:
    for box in r.boxes:
        class_id = int(box.cls[0])
        confidence = float(box.conf[0])
        label = model.names[class_id]
        print(label, ":", confidence * 100)

